// <auto-generated />
using LocalBusiness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusiness.Migrations
{
    [DbContext(typeof(LocalBusinessContext))]
    [Migration("20200821170136_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BusinessAddress");

                    b.Property<string>("BusinessName");

                    b.Property<string>("BusinessType");

                    b.Property<string>("BusinessYelpRating");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            BusinessAddress = "8465 Adams Dr, Greer, SC 29650",
                            BusinessName = "Larry's Laundry",
                            BusinessType = "Laundromat",
                            BusinessYelpRating = "3 Stars"
                        },
                        new
                        {
                            BusinessId = 2,
                            BusinessAddress = "37 Applegate Ave, Merrillville, IN 46410",
                            BusinessName = "Christine Gontarek, Attorney at Law",
                            BusinessType = "Attorney",
                            BusinessYelpRating = "4 stars"
                        },
                        new
                        {
                            BusinessId = 3,
                            BusinessAddress = "9550 Sugar Rd, Phillipsburg, NJ 08865",
                            BusinessName = "Wackey's Burgers & Clown Service",
                            BusinessType = "Restaurant, Entertainment",
                            BusinessYelpRating = "2 Stars"
                        },
                        new
                        {
                            BusinessId = 4,
                            BusinessAddress = "80 Wall Ct, Oak Ridge, TN 37830",
                            BusinessName = "Clump Book Sellers",
                            BusinessType = "Bookstore",
                            BusinessYelpRating = "3 Stars"
                        },
                        new
                        {
                            BusinessId = 5,
                            BusinessAddress = "71 Chestnut Dr, St Albans, NY 11412",
                            BusinessName = "Happy George's Meat Roasters",
                            BusinessType = "Restaurant",
                            BusinessYelpRating = "5 Stars"
                        },
                        new
                        {
                            BusinessId = 6,
                            BusinessAddress = "844 W Wild Horse Ct, Everett, MA 02149",
                            BusinessName = "Lucy's Firing Range",
                            BusinessType = "Firing Range",
                            BusinessYelpRating = "3 Stars"
                        },
                        new
                        {
                            BusinessId = 7,
                            BusinessAddress = "8986 Bear Hill St, Nashville, TN 37205",
                            BusinessName = "Deputy Hawk Filling Station",
                            BusinessType = "Petrol Station",
                            BusinessYelpRating = "5 Stars"
                        },
                        new
                        {
                            BusinessId = 8,
                            BusinessAddress = "83 Ridgewood Ave, Boca Raton, FL 33428",
                            BusinessName = "Laura's Plastics",
                            BusinessType = "Bulk Plastic Vendor",
                            BusinessYelpRating = "2 Stars"
                        },
                        new
                        {
                            BusinessId = 9,
                            BusinessAddress = "660 Cooper St, Tullahoma, TN 37388",
                            BusinessName = "Andy's Boot Barn",
                            BusinessType = "Shoe Store",
                            BusinessYelpRating = "1 Star"
                        },
                        new
                        {
                            BusinessId = 10,
                            BusinessAddress = "736 Birch Hill Ave, Easley, SC 29640",
                            BusinessName = "Uncle Joe's Aromas",
                            BusinessType = "Perfume Vendor",
                            BusinessYelpRating = "1 Star"
                        },
                        new
                        {
                            BusinessId = 11,
                            BusinessAddress = "9659 Amherst Dr, Ypsilanti, MI 48197",
                            BusinessName = "Fast & Fresh Grocery",
                            BusinessType = "Grocery Store",
                            BusinessYelpRating = "4 Stars"
                        },
                        new
                        {
                            BusinessId = 12,
                            BusinessAddress = "92 Grant Dr, Myrtle Beach, SC 29577",
                            BusinessName = "Jefferson Regional Hospital",
                            BusinessType = "Hospital",
                            BusinessYelpRating = "3 Stars"
                        },
                        new
                        {
                            BusinessId = 13,
                            BusinessAddress = "9825 N Jefferson St, Warner Robins, GA 31088",
                            BusinessName = "Angry Dave's Fertilizer",
                            BusinessType = "Garden Supply Store",
                            BusinessYelpRating = "3 Stars"
                        },
                        new
                        {
                            BusinessId = 14,
                            BusinessAddress = "8571 W Theatre Ln, Pataskala, OH 43062",
                            BusinessName = "Westward Contractors",
                            BusinessType = "Construction",
                            BusinessYelpRating = "1 Star"
                        },
                        new
                        {
                            BusinessId = 15,
                            BusinessAddress = "635 Glenridge Ave, Mooresville, NC 28115",
                            BusinessName = "View Bag Video",
                            BusinessType = "Video Rental",
                            BusinessYelpRating = "4 Stars"
                        },
                        new
                        {
                            BusinessId = 16,
                            BusinessAddress = "33 Madison St, Mt Prospect, IL 60056",
                            BusinessName = "Lattakia Restaurant",
                            BusinessType = "Restaurant",
                            BusinessYelpRating = "5 Stars"
                        },
                        new
                        {
                            BusinessId = 17,
                            BusinessAddress = "57 W Hilltop Dr, Missoula, MT 59801",
                            BusinessName = "Twist & Shout",
                            BusinessType = "Record Store",
                            BusinessYelpRating = "2 Stars"
                        },
                        new
                        {
                            BusinessId = 18,
                            BusinessAddress = "278 Boston Dr, Green Cove Spgs, FL 32043",
                            BusinessName = "Zimmer's Lookin' Good Shop",
                            BusinessType = "Tailor",
                            BusinessYelpRating = "5 Stars"
                        },
                        new
                        {
                            BusinessId = 19,
                            BusinessAddress = "647 Somerset Ln, San Jose, CA 95127",
                            BusinessName = "Pig Palace",
                            BusinessType = "Barbecue",
                            BusinessYelpRating = "1 Star"
                        },
                        new
                        {
                            BusinessId = 20,
                            BusinessAddress = "7225 Mayfair Dr, Mankato, MN 56001",
                            BusinessName = "Fancy Freight",
                            BusinessType = "Shipping Company",
                            BusinessYelpRating = "4 Stars"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
